<a href="https://colab.research.google.com/github/sunny9sinha/Blog_Logistic_Regression/blob/main/ordinalLogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install mord

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: mord in /usr/local/lib/python3.9/dist-packages (0.6)

In [6]:
import pandas as pd
import numpy as np
from mord import LogisticAT
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn import preprocessing

# Loading the dataset
data = pd.read_csv('/content/winequality.csv',sep=';')
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [8]:
data['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [24]:
data_selected = pd.concat([data[data['quality'] ==5], data[data['quality']==6], data[data['quality']==7]])

In [25]:
data_selected.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5

In [26]:
# Splitting the dataset into training and testing sets
X = data_selected.iloc[:, :-1]
y = data_selected.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=47)

# Scaling the data
scaler = preprocessing.StandardScaler().fit(X_train)
X_scaled_train = scaler.transform(X_train)
X_scaled_test = scaler.transform(X_test)

# Creating an ordinal logistic regression model
model = LogisticAT(alpha=1.0)

# Fitting the model to the training data
model.fit(X_scaled_train, y_train)

# Predicting the test data
y_pred = model.predict(X_scaled_test)

# Evaluating the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[97 42  0]
 [32 81  4]
 [ 2 38  8]]
              precision    recall  f1-score   support

           5       0.74      0.70      0.72       139
           6       0.50      0.69      0.58       117
           7       0.67      0.17      0.27        48

    accuracy                           0.61       304
   macro avg       0.64      0.52      0.52       304
weighted avg       0.64      0.61      0.59       304